[package]
name = "rtmp"
description = "a powerful live server by Rust ."
version = "0.0.1"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"
readme = "README.md"
categories = ["multimedia", "multimedia::video", 'multimedia::audio']
keywords = ["rtmp", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
bytes = "0.5"
rand = "0.3"
failure = "0.1.1"
hmac = "0.6.2"
sha2 = "0.7.1"
netio = {path = "../../library/netio/"}
tokio-util = { version = "0.3.1", features = ["codec"] }
log = "0.4"

[dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["rt-core", "stream", "sync", "time", "tcp"]