[package]
name = "liverust_lib"
version = "0.1.23"
authors = ["HarlanC <wawacry@qq.com>"]
edition = "2018"
description = "a network io library."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
bytes = "0.5"
rand = "0.3"
failure = "0.1.1"
tokio-util = { version = "0.3.1", features = ["codec"] }
futures = "0.3.5"

[dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["rt-core", "stream", "sync", "time", "tcp"]
