#RTMP server configurations
[rtmp]
enabled = true
port = 1935
[rtmp.pull]
enabled = true
address = "192.168.0.1"
port = 1935
[[rtmp.push]]
enabled = true
address = "192.168.0.2"
port = 1935
[[rtmp.push]]
enabled = true
address = "192.168.0.3"
port = 1935
