#RTMP server configurations
[rtmp]
enabled = true
port = 1935
[rtmp.pull]
enabled = false
address = "192.168.0.1"
port = 1935
[[rtmp.push]]
enabled = true
address = "localhost"
port = 1936
# [[rtmp.push]]
# enabled = true
# address = "192.168.0.3"
# port = 1935
[httpflv]
enabled = true
port = 7000
